name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Upgrade Chocolatey
      run: choco upgrade chocolatey -y
    - name: Setup Advanced Installer
      run: choco install advanced-installer -y
      
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Application\MaxMix.sln -p:Configuration=Debug

    - name: Restore Driver Installer packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build Driver Installer
      run: msbuild Desktop\DriverInstaller\DriverInstaller.sln -p:Configuration=Debug

    - name: Restore Firmware Installer packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build Firmware Installer
      run: msbuild Desktop\FirmwareInstaller\FirmwareInstaller.sln -p:Configuration=Debug
