name: CI_FIRMWAREINSTALLER

on:
  push:
    branches: [ master ]
    paths:
    - 'Desktop/FirmwareInstaller/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'Desktop/FirmwareInstaller/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore Firmware Installer packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build Firmware Installer
      run: msbuild Desktop\FirmwareInstaller\FirmwareInstaller.sln -p:Configuration=Debug
