name: CI_DRIVERINSTALLER

on:
  push:
    branches: [ master ]
    paths:
    - 'Desktop/DriverInstaller/**'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'Desktop/DriverInstaller/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore Driver Installer packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build Driver Installer
      run: msbuild Desktop\DriverInstaller\DriverInstaller.sln -p:Configuration=Debug
