name: Test_Application

on:
  pull_request:
    branches:
      - '*'
    paths:
    - 'Desktop/Application/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup Advanced Installer
      run: choco install advanced-installer --version=17.1.1 -y
    - name: Add Advanced Installer to paths
      run: echo "::add-path::C:/Program Files (x86)/Caphyon/Advanced Installer 17.1.1/bin/x86"
    - name: Register Advanced Installer
      run: AdvancedInstaller.com /register ${{secrets.ADVANCEDINSTALLER_LICENSE}}
      
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Application\MaxMix.sln -p:Configuration=Debug

    - name: Build Installer
      run: AdvancedInstaller.com /build Desktop\Installer\MaxMix.aip 
    
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: true

    - name: Upload Release Assets
      id: upload-release-assets 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: Desktop\Installer\Builds\MaxMix.0.9.1.exe
        asset_name: MaxMix.0.9.1.exe
        asset_content_type: application/zip

    
